apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "uptrace.fullname" . }}
  labels:
    app: uptrace
    {{- include "uptrace.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.uptrace.replicaCount }}
  serviceName: {{ include "uptrace.fullname" . }}
  selector:
    matchLabels:
      app: uptrace
      {{- include "uptrace.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ .Values.uptrace.config | toYaml | sha256sum }}
        sidecar.opentelemetry.io/inject: 'true'
      labels:
        app: uptrace
        {{- include "uptrace.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.uptrace.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "uptrace.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.uptrace.image.repository }}:{{ .Values.uptrace.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.uptrace.image.pullPolicy }}
          volumeMounts:
            - name: config
              mountPath: /etc/uptrace/uptrace.yml
              subPath: uptrace.yml
          ports:
            - name: http
              containerPort: {{ .Values.uptrace.service.http_port }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.uptrace.service.grpc_port }}
              protocol: TCP
          {{ with .Values.uptrace.config.site.addr | urlParse }}
          livenessProbe:
            httpGet:
              path: {{ .path }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .path }}
              port: http
          {{ end }}
          env:
            {{- toYaml .Values.uptrace.env | nindent 12 }}
          envFrom:
            {{- toYaml .Values.uptrace.envFrom | nindent 12 }}
          resources:
            {{- toYaml .Values.uptrace.resources | nindent 12 }}
      {{- with .Values.uptrace.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.uptrace.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.uptrace.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "uptrace.fullname" . }}
